newDirs = ['PEREGRINO_B_ASBUILT_COL_0',
'PEREGRINO_B_ASBUILT_COL_1',
'PEREGRINO_B_ASBUILT_COL_2',
'PEREGRINO_B_ASBUILT_COL_3',
'PEREGRINO_B_ASBUILT_COL_4',
'PEREGRINO_B_ASBUILT_COL_5',
'PEREGRINO_B_ASBUILT_COL_6',
'PEREGRINO_B_ASBUILT_COL_7',
'PEREGRINO_B_ASBUILT_EXTERNO_0',
'PEREGRINO_B_ASBUILT_EXTERNO_1',
'PEREGRINO_B_ASBUILT_EXTERNO_2',
'PEREGRINO_B_ASBUILT_EXTERNO_3',
'PEREGRINO_B_ASBUILT_EXTERNO_4',
'PEREGRINO_B_ASBUILT_EXTERNO_5',
'PEREGRINO_B_ASBUILT_EXTERNO_6',
'PEREGRINO_B_ASBUILT_EXTERNO_7',
'PEREGRINO_B_ASBUILT_INTERNO_0',
'PEREGRINO_B_ASBUILT_INTERNO_1',
'PEREGRINO_B_ASBUILT_DETAILS_1',
'PEREGRINO_B_ASBUILT_DETAILS_0']

from os import path
from pathlib import Path

for _dir in newDirs:
    Path(path.dirname(__file__)+'/'+_dir).mkdir()